https://www.kaggle.com/datasets/vikasukani/parkinsons-disease-data-set
# -*- coding: utf-8 -*-
"""EXPERIMENT_6_Parkinson_Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4Nc3uMmmZmSXUJ91700A5JWyWAybSZd
"""

#AI & ML Experiment 6 : Parkinson's Disease Detection

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

import pandas as pd
import io
from google.colab import files

# Upload file
uploaded = files.upload()

# Get the actual filename (Colab renames if it already exists)
filename = list(uploaded.keys())[0]

# Load the dataset
df = pd.read_csv(io.BytesIO(uploaded[filename]))

# Dataset information
print("✅ Dataset Loaded Successfully!")
print("\nFirst few rows of the dataset:")
print(df.head())

print("\nDataset Shape:", df.shape)
print("\nDataset Information:")
print(df.info())

df.shape

df.info()

df.describe()

df.columns

plt.figure(figsize=(10, 6))
df.status.hist()
plt.xlabel('status')
plt.ylabel('Frequencies')
plt.plot()

plt.figure(figsize=(10, 6))
sns.barplot(x='status', y='NHR', data=df)

plt.figure(figsize=(10, 6))
sns.barplot(x='status', y='HNR', data=df)

plt.figure(figsize=(10, 6))
sns.barplot(x='status', y='RPDE', data=df)

rows = 3
cols = 7
fig, ax = plt.subplots(nrows=rows, ncols=cols, figsize=(16, 4))
col = df.columns
index = 1
for i in range(rows):
    for j in range(cols):
        sns.distplot(df[col[index]], ax=ax[i][j])
        index = index + 1

plt.tight_layout()

df.drop(['name'], axis=1, inplace=True)

X = df.drop(labels=['status'], axis=1)
Y = df['status']
X.head()

X.head()

Y.head()

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=40)
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

log_reg = LogisticRegression().fit(X_train, Y_train)

# predict on train
train_preds = log_reg.predict(X_train)
# accuracy on train
print("Model accuracy on train is: ", accuracy_score(Y_train, train_preds))

# predict on test
test_preds = log_reg.predict(X_test)
# accuracy on test
print("Model accuracy on test is: ", accuracy_score(Y_test, test_preds))
print('-'*50)

# Confusion matrix
print("confusion_matrix train is: ", confusion_matrix(Y_train, train_preds))
print("confusion_matrix test is: ", confusion_matrix(Y_test, test_preds))

RF = RandomForestClassifier().fit(X_train, Y_train)

# predict on train
train_preds2 = RF.predict(X_train)
# accuracy on train
print("Model accuracy on train is: ", accuracy_score(Y_train, train_preds2))

# predict on test
test_preds2 = RF.predict(X_test)
# accuracy on test
print("Model accuracy on test is: ", accuracy_score(Y_test, test_preds2))
print('-'*50)

# Confusion matrix
print("confusion_matrix train is: ", confusion_matrix(Y_train, train_preds2))
print("confusion_matrix test is: ", confusion_matrix(Y_test, test_preds2))

print((Y_test != test_preds2).sum(), '/', ((Y_test == test_preds2).sum() + (Y_test != test_preds2).sum()))

print('KappaScore is: ', metrics.cohen_kappa_score(Y_test, test_preds2))

test_preds2

test_preds2, Y_test

ddf=pd.DataFrame(data=[test_preds2,Y_test])

from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, cohen_kappa_score
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=40)

DT = DecisionTreeClassifier().fit(X_train, Y_train)
# Predict on train data
train_preds3 = DT.predict(X_train)
print("Model accuracy on train is:", accuracy_score(Y_train, train_preds3))

# Predict on test data
test_preds3 = DT.predict(X_test)
print("Model accuracy on test is:", accuracy_score(Y_test, test_preds3))

print("Confusion matrix train:", confusion_matrix(Y_train, train_preds3))
print("Confusion matrix test:", confusion_matrix(Y_test, test_preds3))

# Wrong predictions
print("Wrong predictions:", (Y_test != test_preds3).sum(), '/', ((Y_test == test_preds3).sum() + (Y_test != test_preds3).sum()))

# Kappa Score
print("Kappa Score:", cohen_kappa_score(Y_test, test_preds3))

NB = GaussianNB().fit(X_train, Y_train)
# Predict on train data
train_preds4 = NB.predict(X_train)
print("Model accuracy on train is:", accuracy_score(Y_train, train_preds4))

# Predict on test data
test_preds4 = NB.predict(X_test)
print("Model accuracy on test is:", accuracy_score(Y_test, test_preds4))

print("Confusion matrix train:", confusion_matrix(Y_train, train_preds4))
print("Confusion matrix test:", confusion_matrix(Y_test, test_preds4))

# Wrong predictions
print("Wrong predictions:", (Y_test != test_preds4).sum(), '/', ((Y_test == test_preds4).sum() + (Y_test != test_preds4).sum()))

# Kappa Score
print("Kappa Score:", cohen_kappa_score(Y_test, test_preds4))

KNN = KNeighborsClassifier().fit(X_train, Y_train)
# Predict on train data
train_preds5 = KNN.predict(X_train)
print("Model accuracy on train is:", accuracy_score(Y_train, train_preds5))

# Predict on test data
test_preds5 = KNN.predict(X_test)
print("Model accuracy on test is:", accuracy_score(Y_test, test_preds5))

print("Confusion matrix train:", confusion_matrix(Y_train, train_preds5))
print("Confusion matrix test:", confusion_matrix(Y_test, test_preds5))

# Wrong predictions
print("Wrong predictions:", (Y_test != test_preds5).sum(), '/', ((Y_test == test_preds5).sum() + (Y_test != test_preds5).sum()))

# Kappa Score
print("Kappa Score:", cohen_kappa_score(Y_test, test_preds5))

SVM = SVC(kernel='linear').fit(X_train, Y_train)
# Predict on train data
train_preds6 = SVM.predict(X_train)
print("Model accuracy on train is:", accuracy_score(Y_train, train_preds6))

# Predict on test data
test_preds6 = SVM.predict(X_test)
print("Model accuracy on test is:", accuracy_score(Y_test, test_preds6))

print("Confusion matrix train:", confusion_matrix(Y_train, train_preds6))
print("Confusion matrix test:", confusion_matrix(Y_test, test_preds6))

# Recall Score
print("Recall score:", recall_score(Y_test, test_preds6))

# Wrong predictions
print("Wrong predictions:", (Y_test != test_preds6).sum(), '/', ((Y_test == test_preds6).sum() + (Y_test != test_preds6).sum()))

# Kappa Score
print("Kappa Score:", cohen_kappa_score(Y_test, test_preds6))